kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-read
rules:
- apiGroups: ["inference.networking.x-k8s.io"]
  resources: ["inferencemodels"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["inference.networking.x-k8s.io"]
  resources: ["inferencepools"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
--- 
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-read-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-read
---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  labels:
  name: triton-llama2-7b-pool
spec:
  targetPortNumber: 9000
  selector:
    app: llama-triton
  extensionRef:
    name: inference-gateway-ext-proc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-gateway-ext-proc
  namespace: default
  labels:
    app: inference-gateway-ext-proc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-gateway-ext-proc
  template:
    metadata:
      labels:
        app: inference-gateway-ext-proc
    spec:
      containers:
      - name: inference-gateway-ext-proc
        image: us-central1-docker.pkg.dev/benjaminbraun-gke-dev/triton-test/epp_triton_metrics:latest
        imagePullPolicy: Always
        args:
        - -poolName
        - "triton-llama2-7b-pool"
        - -v
        - "3"
        - -grpcPort
        - "9002"
        - -grpcHealthPort
        - "9003"
        - -allRequestsMetric
        - "nv_trt_llm_request_metrics{request_type=active}"
        - -runningRequestsMetric
        - "nv_trt_llm_request_metrics{request_type=scheduled}"
        - -usedKVCacheBlocksMetric
        - "nv_trt_llm_kv_cache_block_metrics{kv_cache_block_type=used}"
        - -maxKVCacheBlocksMetric
        - "nv_trt_llm_kv_cache_block_metrics{kv_cache_block_type=max}"
        env:
        - name: USE_STREAMING
          value: "false"
        ports:
        - containerPort: 9002
        - containerPort: 9003
        - name: metrics
          containerPort: 9090
        livenessProbe:
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: inference-gateway-ext-proc
  namespace: default
spec:
  selector:
    app: inference-gateway-ext-proc
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: ClusterIP
